"""Presentation provenance: conservative, shared by REST and Socket.IO.

Stored origin is preserved. This classification is an interpretation with a reason,
not a relabeling/migration of historical evidence or an input to response gates.
"""
import json
from functools import lru_cache

from modules.labeling import classify_provenance


@lru_cache(maxsize=1024)
def _classify(description, details_json, origin, timestamp, src, dst):
    try:
        details = json.loads(details_json or '{}')
    except (ValueError, TypeError):
        details = {}
    if not isinstance(details, dict):
        details = {}
    explicit = str(details.get('provenance') or details.get('source_mode') or origin or '').upper()
    if explicit in ('SIMULATED', 'SYNTHETIC', 'EXPERIMENTAL'):
        return explicit, 'Explicit source provenance: ' + explicit.lower()
    if details.get('demo') is True or origin == 'demo':
        return 'DEMO', 'Generated by a demo source; not evidence of a real intrusion.'
    if details.get('simulated') is True or details.get('purple_team') or details.get('source') == 'purple_team':
        return 'SIMULATED', 'Validation or simulation source.'
    classified, reason = classify_provenance(
        description, details_json + ' ' + str(src or '') + ' ' + str(dst or ''),
        details=details, stored_origin=origin, timestamp=timestamp)
    if classified == 'synthetic':
        return 'SYNTHETIC', reason
    if origin == 'real' or details.get('source_mode') == 'real':
        return 'REAL', 'Source recorded real origin; no known synthetic marker. This is not proof of compromise.'
    return 'UNAVAILABLE', 'Source provenance was not recorded reliably; legacy evidence is unverified.'


def provenance(alert):
    details = alert.get('details') or {}
    state, reason = _classify(str(alert.get('description') or ''),
                             json.dumps(details, ensure_ascii=False, default=str),
                             str(alert.get('origin') or ''), str(alert.get('timestamp') or ''),
                             str(alert.get('src_ip') or ''), str(alert.get('dst_ip') or ''))
    return {'state': state, 'reason': reason}


def annotate(alert):
    return {**alert, 'provenance': provenance(alert)}


def sql_provenance(description, details, origin, timestamp, src, dst):
    return _classify(description or '', details or '{}', origin or '', timestamp or '',
                     src or '', dst or '')[0]
